name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      # - name: Run Tests
      #   run: npm test

  build-and-push:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/react-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/react-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # - name: Deploy to DigitalOcean
      #   uses: appleboy/ssh-action@v0.1.3
      #   with:
      #     host: ${{ secrets.DIGITALOCEAN_HOST }}
      #     username: ${{ secrets.DIGITALOCEAN_USER }}
      #     key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
      #     script: |
      #       docker pull ${{ secrets.DOCKER_USERNAME }}/react-app:latest
      #       docker stop react-app || true
      #       docker rm react-app || true
      #       docker run -d -p 3000:80 --name react-app ${{ secrets.DOCKER_USERNAME }}/react-app:latest
